version: "2.1"

services:
  peer1:
    container_name: peer1
    image: benthehorn/block-chain-project
    ports:
      - "3001:3001"
    networks:
      - blockchain
  peer2:
    environment:
      - PEERS=ws://peer1:6001
    container_name: peer2
    image: benthehorn/block-chain-project
    ports:
      - "3002:3001"
    networks:
      - blockchain
    links:
      - peer1:peer1
  peer3:
    environment:
      - PEERS=ws://peer2:6001
      - PEERS=ws://peer1:6001
    container_name: peer3
    image: benthehorn/block-chain-project
    ports:
      - "3003:3001"
    networks:
      - blockchain
    links:
      - peer2:peer2
  peer4:
    environment:
      - PEERS=ws://peer3:6001
      - PEERS=ws://peer2:6001
      - PEERS=ws://peer1:6001
    container_name: peer4
    image: benthehorn/block-chain-project
    ports:
      - "3004:3001"
    networks:
      - blockchain
    links:
      - peer3:peer3

networks:
  blockchain:
    driver: bridge