version: '2'
services:
  peer1:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - "3001:3001"
  peer2:
    environment:
      - PEERS=ws://peer1:6001
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - "3002:3001"
    links:
      - peer1:peer1
  peer3:
    environment:
      - PEERS=ws://peer2:6001
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - "3003:3001"
    links:
      - peer2:peer2
  peer4:
    environment:
      - PEERS=ws://peer3:6001
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - "3004:3001"
    links:
      - peer3:peer3
